# Mapping PSSE 34 components

BUSKEYS = ["I", "NAME", "BASKV", "IDE", "AREA", "ZONE", "OWNER", "VM", "VA", "NVHI", "NVLO", "EVHI", "EVLO"]
LOADKEYS = ["I", "ID", "STAT", "AREA", "ZONE", "PL", "QL", "IP", "IQ", "YP", "YQ", "OWNER", "SCALE", "INTRPT", "DGENP", "DGENQ", "DGENF"]
FIXEDSHUNTKEYS = ["I", "ID", "STATUS", "GL", "BL"]
GENERATORKEYS = [ "I", "ID", "PG", "QG", "QT", "QB", "VS","IREG", "MBASE", "ZR", "ZX", "RT", "XT", "GTAP","STAT", "RMPCT", "PT", "PB", "O1", "F1", "O2", "F2", "O3", "F3","O4", "F4", "WMOD", "WPF", "NREG"]
BRANCHKEYS = ["I", "J", "CKT", "R", "X", "B", "NAME", "RATE1", "RATE2", "RATE3", "RATE4", "RATE5", "RATE6", "RATE7", "RATE8", "RATE9", "RATE10", "RATE11", "RATE12", "GI", "BI", "GJ", "BJ", "STAT", "MET", "LEN", "O1", "F1", "O2", "F2", "O3", "F3", "O4", "F4"]
SYSTEMSWITCHINGDEVICEKEYS = ["I", "J", "CKT", "X", "RATE1", "RATE2", "RATE3", "RATE4", "RATE5", "RATE6", "RATE7", "RATE8", "RATE9", "RATE10", "RATE11", "RATE12", "STAT", "NSTAT", "MET", "STYPE", "NAME"]
TRANSFORMERP1KEYS=["I", "J", "K", "CKT", "CW", "CZ", "CM", "MAG1", "MAG2", "NMETR", "NAME", "STAT", "O1", "F1", "O2", "F2", "O3", "F3", "O4", "F4", "VECGRP", "ZCOD"]
TRANSFORMERP2KEYS = ["R1-2", "X1-2", "SBASE1-2", "R2-3", "X2-3", "SBASE2-3", "R3-1", "X3-1", "SBASE3-1", "VMSTAR", "ANSTAR"]
TRANSFORMERL1KEYS = ["WINDV1", "NOMV1", "ANG1", "RATE1-1", "RATE1-2", "RATE1-3", "RATE1-4", "RATE1-5", "RATE1-6", "RATE1-7", "RATE1-8", "RATE1-9", "RATE1-10", "RATE1-11", "RATE1-12", "COD1", "CONT1", "RMA1", "RMI1", "VMA1", "VMI1", "NTP1", "TAB1", "CR1", "CX1", "CNXA1", "NOD1"]
TRANSFORMERL2KEYS = ["WINDV2", "NOMV2", "ANG2", "RATE2-1", "RATE2-2", "RATE2-3", "RATE2-4", "RATE2-5", "RATE2-6", "RATE2-7", "RATE2-8", "RATE2-9", "RATE2-10", "RATE2-11", "RATE2-12", "COD2", "CONT2", "RMA2", "RMI2", "VMA2", "VMI2", "NTP2", "TAB2", "CR2", "CX2", "CNXA2", "NOD2"]
TRANSFORMERL3KEYS = ["WINDV3", "NOMV3", "ANG3", "RATE3-1", "RATE3-2", "RATE3-3", "RATE3-4", "RATE3-5", "RATE3-6", "RATE3-7", "RATE3-8", "RATE3-9", "RATE3-10", "RATE3-11", "RATE3-12", "COD3", "CONT3", "RMA3", "RMI3", "VMA3", "VMI3", "NTP3", "TAB3", "CR3", "CX3", "CNXA3", "NOD3"]
AREAKEYS = ["I", "ISW", "PDES", "PTOL", "ARNAME"]
TWOTERMINALDCL1KEYS = ["NAME", "MDC", "RDC", "SETVL", "VSCHD", "VCMOD", "RCOMP", "DELTI", "METER", "DCVMIN", "CCCITMX", "CCCACC"]
TWOTERMINALDCL2KEYS = ["IPR", "NBR", "ANMXR", "ANMNR", "RCR", "XCR", "EBASR", "TRR", "TAPR", "TMXR", "TMNR", "STPR", "ICR", "IFR", "ITR", "IDR", "XCAPR", "NDR"]
TWOTERMINALDCL3KEYS=["IPI", "NBI", "ANMXI", "ANMNI", "RCI", "XCI", "EBASI", "TRI", "TAPI", "TMXI", "TMNI", "STPI", "ICI", "IFI", "ITI", "IDI", "XCAPI", "NDI"]
VSCDCLINEL1KEYS = ["NAME", "MDC", "RDC", "O1", "F1", "O2", "F2", "O3", "F3", "O4", "F4"]
VSCDCLINEL2KEYS = ["IBUS", "TYPE", "MODE", "DCSET", "ACSET", "ALOSS", "BLOSS", "MINLOSS", "SMAX", "IMAX", "PWF", "MAXQ", "MINQ", "VSREG", "RMPCT", "NREG"]
IMPEDANCECORRECTIONL1KEYS = ["I", "T1", "Re(F1)", "Im(F1)", "T2", "Re(F2)", "Im(F2)", "T3", "Re(F3)", "Im(F3)", "T4", "Re(F4)", "Im(F4)", "T5", "Re(F5)", "Im(F5)", "T6", "Re(F6)", "Im(F6)"]
IMPEDANCECORRECTIONL2KEYS = ["T7", "Re(F7)", "Im(F7)", "T8", "Re(F8)", "Im(F8)", "T9", "Re(F9)", "Im(F9)", "T10", "Re(F10)", "Im(F10)", "T11", "Re(F11)", "Im(F11)", "T12", "Re(F12)", "Im(F12)"]
MULTITERMINALDCL1KEYS = ["NAME","NCONV","NDCBS","NDCLN","MDC","VCONV","VCMOD","VCONVN"]
MULTITERMINALDCL2KEYS = ["IB", "N", "ANGMX", "ANGMN", "RC", "XC", "EBAS", "TR", "TAP", "TPMX", "TPMN", "TSTP", "SETVL", "DCPF", "MARG", "CNVCOD"]
MULTITERMINALDCL3KEYS = ["IDC","IB","AREA","ZONE","DCNAME","IDC2","RGRND","OWNER"]
MULTITERMINALDCL4KEYS = ["IDC","JDC","DCCKT","MET","RDC","LDC"]
MULTISECTIONLINEKEYS = ["I", "J", "'ID'", "MET", "DUM1", "DUM2", "DUM3", "DUM4", "DUM5", "DUM6", "DUM7", "DUM8", "DUM9"]
ZONEKEYS = ["I","ZONAME"]
INTERAREATRANSFERKEYS = ["ARFROM", "ARTO", "TRID", "PTRAN"]
OWNERKEYS = ["I", "OWNAME"]
FACTSKEYS = ["NAME","I","J","MODE","PDES","QDES","VSET","SHMX","TRMX","VTMN","VTMX","VSMX","IMX","LINX","RMPCT","OWNER","SET1","SET2","VSREF","FCREG","'MNAME'","NREG"]
SWITCHEDSHUNTKEYS = ["I", "MODSW", "ADJM", "ST", "VSWHI", "VSWLO", "SWREG", "RMPCT", "RMIDNT", "BINIT", "N1", "B1", "N2", "B2", "N3", "B3", "N4", "B4", "N5", "B5", "N6", "B6", "N7", "B7", "N8", "B8", "NREG"]
GNEKEYS = [] # Not supported yet
INDUCTIONMACHINEKEYS=["I", "'ID'", "ST", "SC", "DC", "AREA", "ZONE", "OWNER", "TC", "BC", "MBASE", "RATEKV", "PC", "PSET", "H", "A", "B", "D", "E", "RA", "XA", "XM", "R1", "X1", "R2", "X2", "X3", "E1", "SE1", "E2", "SE2", "IA1", "IA2", "XAMULT"]
SUBSTATIONKEYS = []

DATA = {
    "BUS": BUSKEYS,
    "LOAD": LOADKEYS,
    "FIXED SHUNT": FIXEDSHUNTKEYS,
    "GENERATOR": GENERATORKEYS,
    "BRANCH": BRANCHKEYS,
    "SYSTEM SWITCHING DEVICE": SYSTEMSWITCHINGDEVICEKEYS,
    "TRANSFORMER": [TRANSFORMERP1KEYS, TRANSFORMERP2KEYS, TRANSFORMERL1KEYS, TRANSFORMERL2KEYS, TRANSFORMERL3KEYS],
    "AREA": AREAKEYS,
    "TWO-TERMINAL DC": [TWOTERMINALDCL1KEYS, TWOTERMINALDCL2KEYS, TWOTERMINALDCL3KEYS],
    "VSC DC LINE": [VSCDCLINEL1KEYS, VSCDCLINEL2KEYS],
    "IMPEDANCE CORRECTION": [IMPEDANCECORRECTIONL1KEYS, IMPEDANCECORRECTIONL2KEYS],
    "MULTI-TERMINAL DC": [MULTITERMINALDCL1KEYS, MULTITERMINALDCL2KEYS, MULTITERMINALDCL3KEYS, MULTITERMINALDCL4KEYS],
    "MULTI-SECTION LINE": MULTISECTIONLINEKEYS,
    "ZONE": ZONEKEYS,
    "INTER-AREA TRANSFER": INTERAREATRANSFERKEYS,
    "OWNER": OWNERKEYS,
    "FACTS": FACTSKEYS,
    "SWITCHED SHUNT": SWITCHEDSHUNTKEYS,
    "GNE": GNEKEYS,
    "INDUCTION MACHINE": INDUCTIONMACHINEKEYS,
    "SUBSTATION": SUBSTATIONKEYS
    }
    
MULTILINECOMPONENTS = ["TRANSFORMER", "TWO-TERMINAL DC", "VSC DC LINE", "IMPEDANCE CORRECTION", "MULTI-TERMINAL DC"]
